export const amenities = {
	PARTY_HALL: "Salão de Festas",
	FURNISHED: "Mobiliado",
	FIREPLACE: "Lareira",
	POOL: "Piscina",
	BARBECUE_GRILL: "Churrasqueira",
	AIR_CONDITIONING: "Ar condicionado",
	ELEVATOR: "Elevador",
	PLAYGROUND: "Playground",
	GATED_COMMUNITY: "Condomínio fechado",
	SPORTS_COURT: "Quadra poli-esportiva",
	PETS_ALLOWED: "Aceita animais",
	LAUNDRY: "Lavanderia",
	TENNIS_COURT: "Quadra de tênis",
	GYM: "Academia",
	AMERICAN_KITCHEN: "Cozinha americana",
	SAUNA: "Sauna",
	CINEMA: "Cinema",
	ELECTRONIC_GATE: "Portão eletrônico",
	GARDEN: "Jardim",
	BICYCLES_PLACE: "Bicicletário",
};
